### ISSUE TITLE
Data Extraction

### ISSUE THREAD

**Issue by cx1111** [nalinimsingh/HST.953#1]
Use this thread to discuss details of data extraction. The README.md file will be updated to reflect decisions.

**Comment by cx1111** [comment]
## Allocation

Nalini
- [x] MAP
- [x] Pressors
- [x] Lactate

Chen
- [x] Age, eth, sex
- [x] Death, LOS>3
- [x] Creatinine
- [x] Urine output

**Comment by cx1111** [comment]
Matthieu suggested that it would be rather impossible to filter out patients who have end stage renal disease upon admission according to the RIFLE because that requires knowledge of their creatinine/urine for several weeks. 

Therefore we are using either of: creatinine>1.2, or the ICD9 code for chronic kidney disease, to filter out patients.

**Comment by nalinimsingh** [comment]
Ok, sounds good to me! I see you created a final_extraction.sql -- are you writing that now? Or should I start? Either way works equally well for me.

**Comment by nalinimsingh** [comment]
Also, @juliannc -- which vasopressors in particular are we interested in for this particular study?

**Comment by cx1111** [comment]
I'm going to sleep now 😶 but was planning to work on it after work tomorrow. Feel free to start.

**Comment by nalinimsingh** [comment]
Ok sounds good. Thanks, Chen!

**Comment by juliannc** [comment]
I saw you were pulling Isuprel it is not a Vasopressor it elevates the heart rate.

Juliann

________________________________

**Comment by nalinimsingh** [comment]
Ok, thanks for the list! I was just using a list from one of Alistair's previous scripts (which included Isuprel) until I knew exactly which ones to pull for our project. I'll update the script this evening when I'm home.

**Comment by juliannc** [comment]
Nalini,

Under urine output pull  is "TF Residual"  this is not urien out put do not pull.

Juliann

________________________________

**Comment by juliannc** [comment]
Nalini,

Sorry I have not looked at you pull until know I am not familiar with GITHUB and  did not see them before

Dobutamin, milrinone, should also not be pulled.

Have a nice Thankgiving.

Juliann?

________________________________

**Comment by nalinimsingh** [comment]
@juliannc: Thanks for your comments! 

I've updated the list of vasopressors we're pulling to be: Dopamine, Norepinephrine, Phenylephrine, Epinephrine, Vasopressin per your email. I searched the repo for Isuprel, but found no results -- where did you see us pulling this?

I've also made the change to not pull TF Residual.

**Comment by nalinimsingh** [comment]
@cx1111: I started writing final_extraction.sql, but realized I can't actually test it. I'm running queries against a remote copy of mimic and don't have the appropriate permissions to create views. I wrote a draft for my scripts that I roughly think is correct, but you may need to help me with generating the CSV we use to do the data analysis. Let me know if there are any issues.

Also, right now, I'm just pulling all of the MAP measurements, as I think we may want to try different MAP feature vectors. I'll try to think of an intelligent way to consolidate these with SQL, but worst case, I can do the processing in Python.

**Comment by cx1111** [comment]
Sure, I'll be running tests as I go along. I'm also thinking of how to organize data such as urine and creatinine into a more efficient manner. 

I'm trying to fill in missing icustay_id and hadm_ids right now for lab measurements but it's taking a really long time to query.

**Comment by cx1111** [comment]
One thing of note, there are a bunch of creatinine measurements which lie out of hospital admission ids. eg. subject 21 has measurements in 2134-08-20 10:25:00 and 2134-09-28 22:30:00 whereas their only hadm of the year is between 2134-09-11 12:17:00 | 2134-09-24 16:15:00. 

So as I try to fill in missing creatinine hadm_id and urine hadm+icustayids using the admissions and icustays tables, what should we do with the ones which don't get assigned one? Toss them? Also I suppose we should give a window of +/- 12h or 1 day.

**Comment by juliannc** [comment]
?Chen,

I am notthe  sure but I think you are talking about patient that arrive in the hospital and there identity is in question they are called EU-Critical then a first name like Jane. When they are later identified If they have previously been a patient at a BIDMC facility they MERGE the records so you find two  ID number for the same patient the first will be seen for 1-2 days of maybe just a few hours.  This is a common occcurence their should be a script already available to help with this.

Juliann

________________________________

**Comment by cx1111** [comment]
Thanks @juliannc, that makes sense. I ended up doing table unions which get rid of repeated values so it should work out.

**Comment by cx1111** [comment]
Mostly done with the exporting. Some considerations that I put into my code which can easily be changed upon discussion:

- The 'admission' creatinine values I arbitrarily chose were the max values of all creatinine measurements that were from 2 hours after the hospital admission to any time before. 
- The 'fuzzy windows' I chose to fill in missing hadm or icustay ids were the real ones +/- up to 12 hours. 
- I tried to give every  final 'measurement' we are exporting to tables an icustay id via fuzzy windows and removed all values which could not be associated with an icustay. This additional criteria removed 0 map values, 1000/1 million urine values, and 36000/130000 creatinine values. If we decide to we can easily keep measurements even if they're not matched to an icustay by using left join instead of inner join.

**Comment by cx1111** [comment]
@nalinimsingh 

I've exported the first version of the tables. One was too big so I'll put them here from now: https://drive.google.com/open?id=0B-IsdtOumwVEZU52MDNXMzlSZUE

Thanks for your patience!

**Comment by juliannc** [comment]
Hi I looked at your data,

Thank you  for all your hard work.

 MAP values of = to < 30 or  => 200 are not valid.

 The urine out value of 1000 or large may be not be an hourly output but the amount of urine they put out prior to arrival in ICU we have a  section for preICU output but some time people put it in the urine output  column at the hour of admission. We may want to  collect urine  output starting with 2nd hour after arrival in ICU.

The Creatine pulled is that the Creatine available just prior to admission or the first creatine obtained?

 Do you have any to meet this week to go over data So I can start  working onthe analysis.

I can meet Tuesday afternoon, wednesday morning or any time thursday or Friday.

Juliann


@nalinimsingh<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_nalinimsingh&d=CwMFaQ&c=WknmpdNpvrlj2B5K1aWVqL1SOiF30547pqSuOmtwXTQ&r=zdSU84yBy3j2OzZr9NEwh9M8teYlU_8vtGr4h9UKx-Q&m=xaS5hcJxHsagCZf0Kw60It4qY8tWVRLLpSboBdZjU74&s=dUdNqcvEnCW0uuLivxGQAwRZEj9z8i3Dkw3Waqj8s3w&e=>

I've exported the first version of the tables. One was too big so I'll put them here from now: https://drive.google.com/drive/folders/0B-IsdtOumwVEZU52MDNXMzlSZUE<https://urldefense.proofpoint.com/v2/url?u=https-3A__drive.google.com_drive_folders_0B-2DIsdtOumwVEZU52MDNXMzlSZUE&d=CwMFaQ&c=WknmpdNpvrlj2B5K1aWVqL1SOiF30547pqSuOmtwXTQ&r=zdSU84yBy3j2OzZr9NEwh9M8teYlU_8vtGr4h9UKx-Q&m=xaS5hcJxHsagCZf0Kw60It4qY8tWVRLLpSboBdZjU74&s=l3DuH3wCiif37AMj8R7g804s2dru7wEyK01t1vYe4s4&e=>

Thanks for your patience!

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_nalinimsingh_HST.953_issues_1-23issuecomment-2D263156570&d=CwMFaQ&c=WknmpdNpvrlj2B5K1aWVqL1SOiF30547pqSuOmtwXTQ&r=zdSU84yBy3j2OzZr9NEwh9M8teYlU_8vtGr4h9UKx-Q&m=xaS5hcJxHsagCZf0Kw60It4qY8tWVRLLpSboBdZjU74&s=MrsbmZrUSvIL0BKqdQJfQzJchronK-4iNRTGGoBo06k&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AVIsW-2DjjvuVbrZblYO7rnJ75Z0-2DR2LHrks5rChTXgaJpZM4Kt22B&d=CwMFaQ&c=WknmpdNpvrlj2B5K1aWVqL1SOiF30547pqSuOmtwXTQ&r=zdSU84yBy3j2OzZr9NEwh9M8teYlU_8vtGr4h9UKx-Q&m=xaS5hcJxHsagCZf0Kw60It4qY8tWVRLLpSboBdZjU74&s=ezcIezFsfP04FKN3A3bJdZRYEXFiKH65hf53L1yKlPc&e=>.

________________________________

This message is intended for the use of the person(s) to whom it may be addressed. It may contain information that is privileged, confidential, or otherwise protected from disclosure under applicable law. If you are not the intended recipient, any dissemination, distribution, copying, or use of this information is prohibited. If you have received this message in error, please permanently delete it and immediately notify the sender. Thank you.

**Comment by nalinimsingh** [comment]
Ok, thanks @juliannc -- I've limited the MAP query to only pull values between 30 and 200. I'm not sure about the other questions -- @cx1111 did those. 

I'm available to meet on Wednesday morning, Thursday afternoon, or anytime on Friday except for 1 PM - 2 PM. Let me know what works!

**Comment by nalinimsingh** [comment]
Oh, also, @cx1111 -- I noticed the MAP query takes a really long time. Instead of creating a MV with all of the values of MAP like we did for the other measurements, do you want me to rewrite the query to only match the subject_id, icustay_id's from our cohort? Let me know.

Also, I'll create an issue/edit the README with my preliminary ideas for the data analysis sometime tonight.

Thanks!

**Comment by cx1111** [comment]
Thanks for the MAP reminder Juliann. Regarding the urine values, I pull all urine values and then keeping the ones that lie within +/- 12h of their icustays. Same for creatinine values. The 'admission creatinine' values I was talking about are the subset of these creatinine values which range from +2 hours to any time before the icu entry time. I just made that +2 up. We use the 'admission creatinine' > 1.2 criteria to create our final cohort along with the ICD9 ckd codes. 

Nalini there's no need to edit the map query. I already filter every measurement table (urine, creatinine, MAP) in the final extraction script to the final cohort before writing to tables. If you write additional conditions, I doubt it will make the query any faster because it will actually have to do more computations (same in total compared to filtering by cohort later), but it will make the MV smaller. I don't care about disc space on my desktop and we'll drop all the MV in the end anyway. It makes more sense to me logically to isolate all measurements to their own scripts before filtering them out. 

Also after work I'll export the charttimes as number of minutes after icu admittime instead. Forgot that yesterday. 

I recommend meeting on Thursday afternoon so we all have some time to look over the data first.

**Comment by cx1111** [comment]
Also pedantic detail: you adding the map outlier filter criteria to the original MAP query probably takes longer compared to if you added it to the final extraction script after the maps are filtered by cohort. The cohort filter reduces the count by 2/3 whereas the outlier filter only removes about 0.2%. Hence you're performing more calculations in total. 

Doesn't matter too much, it took me a few minutes to run your map script. I've updated the files on the google drive now.

**Comment by juliannc** [comment]
? Nalini,

Why don't we meet on Wednesday morning that way we can also meet  again Fiday if needed.  Can anyone else meet Wednesday to  lok at the data and start discussig the analysis.

Juliann

________________________________
